In [2]:
voc = list("abcdefghijklmnop")
restriction = list("acegi")
voc = set([w for w in voc if [r in w for r in restriction]])
voc

{'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p'}

In [2]:
import numpy as np
def cos_sim(v1, v2):
    if not v1.shape == v2.shape:
        raise ValueError
    if v1.ndim == 1:
        axis = 0
    elif v1.ndim == 2:
        axis = 1
    else:
        raise ValueError
    val = (v1 * v2).sum(axis=axis) / (np.linalg.norm(v1, axis=axis) * np.linalg.norm(v2, axis=axis))
    # sometimes identical vectors produce 1.0000001. floating point problem?
    if v1.ndim == 1:
        return min(val,1)
    else:
        return np.minimum(val, np.ones_like(val))

def angular_distance(v1, v2):
    return np.arccos(cos_sim(v1,v2)) / np.pi

In [3]:
a=np.array([1,2,3,1,5])
b=np.array([1,2,6,1,2])

In [4]:
cos_sim(a, b)

0.7926290870042666

In [5]:
angular_distance(a,b)

0.2087117387003492

In [6]:
cos_sim(a,a)

0.9999999999999998

In [7]:
angular_distance(a,a)

6.707879276254074e-09

In [8]:
c=np.array([[1,2,3,1,5], [5,1,1,1,5]])
d=np.array([[1,1,2,1,1], [5,5,6,1,1]])

In [9]:
cos_sim(c, d)

array([0.83852549, 0.61499278])

In [10]:
angular_distance(c,d)

array([0.1834181 , 0.28915891])

In [11]:
cos_sim(d,d)

array([1., 1.])

In [13]:
angular_distance(c,c)

array([6.70787928e-09, 0.00000000e+00])