In [1]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
from difflib import SequenceMatcher
from pathlib import Path
from sklearn.utils.extmath import softmax
from collections import Counter

In [24]:
def PairwiseMeanSimilarity(v, v_list):
    
    pairwise = cosine_similarity(v, v_list)
    pairwise_mean = pairwise.mean()
    
    return pairwise_mean

In [23]:
import random
random.seed(545)

In [25]:
INGROUPvec = np.random.rand(100,200)
OUTGROUPvec = np.random.rand(100,200)

In [32]:
INGROUPvec

array([[0.2172707 , 0.00712897, 0.24449651, ..., 0.83235149, 0.13504824,
        0.61686711],
       [0.95523272, 0.39356687, 0.5962928 , ..., 0.33591865, 0.59654356,
        0.02908471],
       [0.79190772, 0.67602216, 0.30493123, ..., 0.54488829, 0.27813345,
        0.9899103 ],
       ...,
       [0.29067266, 0.04669347, 0.68562213, ..., 0.60134232, 0.89363371,
        0.61430547],
       [0.26733178, 0.21695341, 0.13997597, ..., 0.00394275, 0.50817862,
        0.08221333],
       [0.59096537, 0.23546163, 0.02239672, ..., 0.93640004, 0.81226051,
        0.21355868]])

In [33]:
OUTGROUPvec

array([[0.59048051, 0.33011481, 0.73608339, ..., 0.29008105, 0.10330381,
        0.85598549],
       [0.5543277 , 0.53350495, 0.91281143, ..., 0.08853272, 0.68920684,
        0.67455294],
       [0.61126471, 0.75190416, 0.44058   , ..., 0.27827879, 0.21339451,
        0.4827385 ],
       ...,
       [0.19688495, 0.64579621, 0.81101092, ..., 0.43552751, 0.10799537,
        0.76472184],
       [0.76168765, 0.5790191 , 0.53916664, ..., 0.01185267, 0.04735448,
        0.29872547],
       [0.87151886, 0.07701488, 0.3468445 , ..., 0.82806527, 0.56608493,
        0.40712474]])

In [26]:
ING_centroid  = INGROUPvec.mean(axis=0)
OUTG_centroid = OUTGROUPvec.mean(axis=0)

In [34]:
ING_centroid

array([0.48792211, 0.51513914, 0.52696013, 0.5007329 , 0.50199136,
       0.52067867, 0.47363326, 0.48679768, 0.54394458, 0.51131096,
       0.44117335, 0.47859996, 0.50517093, 0.5484199 , 0.51779492,
       0.514715  , 0.49315738, 0.49285313, 0.43438299, 0.51745772,
       0.45089405, 0.50840767, 0.48749137, 0.46699853, 0.46975659,
       0.49463619, 0.47631965, 0.46081408, 0.4616951 , 0.46392918,
       0.48064131, 0.46902646, 0.54052732, 0.53984799, 0.46382866,
       0.50232565, 0.53673625, 0.51914922, 0.46748803, 0.4904556 ,
       0.5107916 , 0.48391384, 0.49585766, 0.46817017, 0.50894149,
       0.53634707, 0.52662793, 0.51204157, 0.4661926 , 0.51424022,
       0.46080677, 0.45981049, 0.51621597, 0.49840539, 0.52016736,
       0.4945126 , 0.47071197, 0.52339935, 0.48592672, 0.46224249,
       0.52749432, 0.4614179 , 0.53983127, 0.52822623, 0.54053787,
       0.47232089, 0.48808399, 0.46407434, 0.48875619, 0.47791957,
       0.56423342, 0.52039541, 0.47716302, 0.56535214, 0.50784

In [35]:
OUTG_centroid

array([0.50407916, 0.50130337, 0.47110288, 0.43439369, 0.47824742,
       0.48054735, 0.45570856, 0.494729  , 0.52588744, 0.50018744,
       0.47615788, 0.51158723, 0.42472515, 0.48465723, 0.46521619,
       0.49063951, 0.44068559, 0.50686451, 0.49937648, 0.55227681,
       0.47560668, 0.49485617, 0.55865959, 0.49192231, 0.44797694,
       0.52878817, 0.48886871, 0.52951377, 0.50875985, 0.48787162,
       0.45507865, 0.48454867, 0.50687343, 0.46304982, 0.48813896,
       0.45719142, 0.50546686, 0.54365077, 0.51507321, 0.50306234,
       0.48873294, 0.52243068, 0.45594615, 0.50002969, 0.49987238,
       0.4897658 , 0.50370358, 0.42813065, 0.48565494, 0.50974287,
       0.53684699, 0.51926793, 0.51798135, 0.49536583, 0.48056335,
       0.51579094, 0.49425225, 0.5141021 , 0.5023613 , 0.52146025,
       0.47733518, 0.51127348, 0.50637378, 0.45743674, 0.51277585,
       0.4384515 , 0.51125436, 0.52380274, 0.50287588, 0.48812867,
       0.46423852, 0.45170761, 0.50909431, 0.44820038, 0.50292

With random numbers, the mean will converge to 0.5

In [27]:
#vector = np.random.rand(1,200)

In [28]:
results = []
for year in range(11):
    vector = np.random.rand(1,200)

    i_cnt = cosine_similarity(vector.reshape(1,-1), ING_centroid.reshape(1,-1))[0][0] 
    o_cnt = cosine_similarity(vector.reshape(1,-1), OUTG_centroid.reshape(1,-1))[0][0]

    i_pwn = PairwiseMeanSimilarity(vector.reshape(1, -1), INGROUPvec)
    o_pwn = PairwiseMeanSimilarity(vector.reshape(1, -1), OUTGROUPvec)
    
    d = {
    "I-cnt": i_cnt,
    "O-cnt": o_cnt ,
    "cnt-ssc": i_cnt / (i_cnt + o_cnt),
    "cnt-smx": softmax([[i_cnt, o_cnt]])[0][0],

    "I-pwn": i_pwn,
    "O-pwn": o_pwn,
    "pwn-ssc": i_pwn / (i_pwn + o_pwn),
    "pwn-smx": softmax([[i_pwn, o_pwn]])[0][0]
    }
    results.append(d)

In [29]:
df = pd.DataFrame(results, index=list(range(2000, 2011))).transpose()

In [37]:
df.round(3)

2000   2001   2002   2003   2004   2005   2006   2007   2008   2009  \
I-cnt    0.856  0.863  0.878  0.870  0.868  0.861  0.864  0.881  0.879  0.844   
O-cnt    0.857  0.868  0.877  0.868  0.863  0.858  0.866  0.882  0.880  0.845   
cnt-ssc  0.500  0.499  0.500  0.500  0.502  0.501  0.499  0.500  0.500  0.500   
cnt-smx  0.500  0.499  0.500  0.500  0.501  0.501  0.499  0.500  0.500  0.500   
I-pwn    0.743  0.749  0.762  0.755  0.754  0.748  0.750  0.765  0.763  0.732   
O-pwn    0.744  0.753  0.762  0.754  0.749  0.745  0.752  0.765  0.764  0.733   
pwn-ssc  0.500  0.499  0.500  0.500  0.501  0.501  0.499  0.500  0.500  0.500   
pwn-smx  0.500  0.499  0.500  0.500  0.501  0.501  0.499  0.500  0.500  0.500   

          2010  
I-cnt    0.867  
O-cnt    0.865  
cnt-ssc  0.501  
cnt-smx  0.500  
I-pwn    0.752  
O-pwn    0.751  
pwn-ssc  0.500  
pwn-smx  0.500

In [36]:
df.transpose().corr().round(3)

I-cnt  O-cnt  cnt-ssc  cnt-smx  I-pwn  O-pwn  pwn-ssc  pwn-smx
I-cnt    1.000  0.969    0.152    0.150  1.000  0.970    0.150    0.147
O-cnt    0.969  1.000   -0.097   -0.099  0.969  1.000   -0.099   -0.101
cnt-ssc  0.152 -0.097    1.000    1.000  0.151 -0.094    0.999    1.000
cnt-smx  0.150 -0.099    1.000    1.000  0.149 -0.096    0.999    0.999
I-pwn    1.000  0.969    0.151    0.149  1.000  0.970    0.149    0.146
O-pwn    0.970  1.000   -0.094   -0.096  0.970  1.000   -0.095   -0.098
pwn-ssc  0.150 -0.099    0.999    0.999  0.149 -0.095    1.000    1.000
pwn-smx  0.147 -0.101    1.000    0.999  0.146 -0.098    1.000    1.000

Although *X*-cnt and *x*-pwn are different, their correlation is almost perfect.